### ISSUE TITLE
Generate convergence plots and/or statistics

### ISSUE THREAD

**Issue by Gabriel-p** [sofi1256/Repositorio-adscripci-n#5]
A bayesian MCMC inference method needs to have converged to be sure that the space of the parameters has been explored properly (ie: the MCMC chains have converged). There are [several statistics and plots](https://www.statlect.com/fundamentals-of-statistics/Markov-Chain-Monte-Carlo-diagnostics) that can be used to check for convergence. `emcee` uses the [autocorrelation time](https://emcee.readthedocs.io/en/stable/tutorials/autocorr/) and it has [integrated methods to estimate it](https://emcee.readthedocs.io/en/stable/tutorials/monitor/).

A common convergence test plot is the trace plot. This along with many others can be generated using the [arviz](https://python.arviz.org/) package

**Comment by sofi1256** [comment]
I created a new branch adding functions to make trace plots and autocorrelation function plots. This new brand also includes the improvements for issue #3, and some misc quality of life improvements.
